<a href="https://colab.research.google.com/github/GermanStanzione/TT-2C2025-Data-Analitycs-Notebooks/blob/main/After_class_5/Mia/After_class_5_tratamiento_duplicados_nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad 1


## Eliminación de Duplicados y Tratamiento de Datos Faltantes
Contamos con un conjunto de datos ficticio de una tienda en línea que contiene información sobre clientes, incluyendo nombre, edad y correo electrónico. Realizar las siguientes tareas:
* Cargar el conjunto de datos.
* Identificar y eliminar las filas duplicadas.
* Manejar los datos faltantes en la columna de edad, evaluando cuál es la mejor decisión, considerando que vamos a realizar un análisis enfocado en grupos etarios de los clientes. Evaluar el impacto sobre el análisis si:
  * Se eliminan las filas que no contienen la edad.
  * Se completa el dato con la media de la columna.

In [1]:
# Importamos librerias
import pandas as pd

In [2]:
# Importamos datos de Google Sheets
ID_planilla = '13ufG0CQqpozGhJfh8t3T-01p4lcPPZa26TrrWhQux3c'
URL = f'https://docs.google.com/spreadsheets/d/{ID_planilla}/gviz/tq?tqx=out:csv&sheet='
df = pd.read_csv(URL)
df.head()

                Nombre  Edad                     Email
0         Elonore Over  40.0         eoverh6@ocn.ne.jp
1     Jacquette Gillbe  49.0       jgillbeb8@diigo.com
2  Sheelah Olechnowicz  61.0    solechnowiczch@mlb.com
3       Morris Bilovus  32.0  mbilovus3q@artisteer.com
4          Erda Geipel  60.0      egeipelj5@jalbum.net

In [4]:
# Veamos la estructura del dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  1032 non-null   object
 1   Edad    973 non-null    float64
 2   Email   1032 non-null   object
dtypes: float64(1), object(2)
memory usage: 24.3+ KB

### Eploracion y tratamiento de duplicados

In [8]:
# Cuantificamos los registros duplicados
df.duplicated().sum()

np.int64(32)

In [11]:
# Visualizar los registros duplicados
#df[df.duplicated(keep=First)].sort_values(by='Nombre')
df[df.duplicated(keep=False)].sort_values(by='Nombre')
#df[df.duplicated(keep=Last)].sort_values(by='Nombre')

                Nombre  Edad                       Email
577    Arnoldo Britney  52.0  abritney8f@arstechnica.com
838    Arnoldo Britney  52.0  abritney8f@arstechnica.com
535       Berny Rawlin  49.0          brawlin94@time.com
402       Berny Rawlin  49.0          brawlin94@time.com
907    Candace Ruperti   NaN         cruperti8t@furl.net
...                ...   ...                         ...
828       Veda Sherman  33.0          vsherman8y@mac.com
839          Vina Mein  64.0         vmein8o@sina.com.cn
1022         Vina Mein  64.0         vmein8o@sina.com.cn
607   Welch Addionizio  57.0       waddionizio91@unc.edu
621   Welch Addionizio  57.0       waddionizio91@unc.edu

[64 rows x 3 columns]

In [13]:
# Usamos drop_duplicates() para eliminar los registros duplicados VER INPLACE
df_pp1 = df.drop_duplicates(keep='First')
df_pp1[df_pp1["Nombre"]== "Arnoldo Britney"]

ValueError: keep must be either "first", "last" or False

### Eploracion y tratamiento de nulos

In [14]:
# Ver si hay datos nulos y cuantos
df.isnull().sum()

Nombre     0
Edad      59
Email      0
dtype: int64

In [16]:
# Visualizar los nulos ANY AXIS = 1
df[df.isnull().any(axis=1)] [["Nombre","Edad"]]

                  Nombre  Edad
23    Timotheus Meggison   NaN
32       Dominga Dewdney   NaN
44          Peggy Songer   NaN
52        Dewey McCulley   NaN
53          Phil Triggol   NaN
74         Lilyan Dulton   NaN
78       Janina Florence   NaN
88             Del Lente   NaN
110          Wilone Sked   NaN
151        Ronnica Mabey   NaN
163      Margareta Likly   NaN
189      Candace Ruperti   NaN
212    Bancroft McVanamy   NaN
229     Marie-ann Kilius   NaN
252    Veronika McLaggan   NaN
261    Caritta Hardwidge   NaN
266       Jolene Laviste   NaN
267        Pippo Dagless   NaN
306   Anthiathia Phorsby   NaN
311       Olivette Myall   NaN
327         Lindy Klebes   NaN
361          Kipp Godney   NaN
364        Beale Cabbell   NaN
368      Chaddie Rylance   NaN
449       Traci Di Boldi   NaN
469         Fiona Pulham   NaN
501     Pinchas McOrkill   NaN
504      Lurleen Sewards   NaN
530    Garrett Antognoni   NaN
550       Cullen Ruzicka   NaN
568     Selia Lorenzetto   NaN
585     Yolane Gracewood   NaN
617          Gail Oxtiby   NaN
620       Ericka Seagood   NaN
627    Mehetabel Stanger   NaN
637        Hussein Niese   NaN
659      Arlyn Jacobsohn   NaN
698   Consolata Crommett   NaN
759      Kristen Scoates   NaN
763          Dore Kidson   NaN
767      Kathi Blockwell   NaN
775         Shelby Beric   NaN
777         Alwyn Ashall   NaN
807      Felecia Asquith   NaN
826        Dorelle Jewar   NaN
862      Marleen Stirrip   NaN
874        Birgit Deppen   NaN
906     Rodolph Petracco   NaN
907      Candace Ruperti   NaN
937        Yule Sparwell   NaN
945       Mallissa Skews   NaN
959        Ronnica Mabey   NaN
961      Roderic Musicka   NaN
965      Stirling Tenman   NaN
987       Ethel Crichten   NaN
989         Shea Lapwood   NaN
1001      Laureen Mahony   NaN
1009       Kamilah Brame   NaN
1015   Derick Scorthorne   NaN

In [18]:
# Eliminar los nulos VER SUBSET Y HOW
df_nueva = df.dropna()
df_nueva.info()

<class 'pandas.core.frame.DataFrame'>
Index: 973 entries, 0 to 1031
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  973 non-null    object
 1   Edad    973 non-null    float64
 2   Email   973 non-null    object
dtypes: float64(1), object(2)
memory usage: 30.4+ KB

In [ ]:
# Visualizamos despues de eliminar

In [ ]:
# Reemplazar nulos por un valor fijo
df_nueva = df.fillna(0)
df_nueva.info()

In [ ]:
# Reemplazar nulor por la media/mediana

# Actividad 2

In [ ]:
# Importamos datos de Google Sheets
ID_planilla = '170GDFJKpZEaBbA48mII018sW6qBOGz2X4UlV4HNQaWo'
URL = f'https://docs.google.com/spreadsheets/d/{ID_planilla}/gviz/tq?tqx=out:csv&sheet='
df = pd.read_csv(URL)
df.head()

In [ ]:
df.info()

In [ ]:
# Convertir tipo de dato de Precio

In [ ]:
# Normalizar